image: docker:latest

services:
  - docker:dind

docker-build:
  image: decentraland/ci-node:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - source dcl-env
    - pip install awscli
    - export AWS_REGION="$CI_REGISTRY_REGION"
    - aws ecr get-login-password --region "$CI_REGISTRY_REGION" | docker login --username AWS --password-stdin "$CI_REGISTRY_REPOSITORY_AWS"
  script:
    - docker build --pull -t "$CI_REGISTRY_REPOSITORY_AWS/transactions-server:$CI_COMMIT_SHA" .
    - docker build --pull -t "$CI_REGISTRY_REPOSITORY_AWS/transactions-server:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_REPOSITORY_AWS/transactions-server:$CI_COMMIT_SHA"
    - docker push "$CI_REGISTRY_REPOSITORY_AWS/transactions-server:$CI_COMMIT_REF_SLUG"

deploy-infra:
  stage: deploy
  image: decentraland/ci-node:latest
  only:
    - master
    - staging
    - release
  script:
    - dcl-lock-sync
    - cd .ci && npm install && cd node_modules/dcl-ops-lib && dcl-up services-transactions-server
    - cd ..
    - dcl-sync-release
    - dcl-announce-docker-build
