image: docker:latest

services:
  - docker:dind

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" .
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

deploy-infra:
  stage: deploy
  image: decentraland/ci-node:latest
  only:
    - master
    - staging
    - release
  script:
    - dcl-lock-sync
    - cd .ci && npm install && cd node_modules/dcl-ops-lib && dcl-up services-transactions-server
    - cd ..
    - dcl-sync-release
    - dcl-announce-docker-build
