image: docker:latest

services:
  - docker:dind

deploy-infra:
  stage: deploy
  image: decentraland/ci-node:latest
  only:
    - master
    - staging
    - release
  script:
    - dcl-lock-sync
    - cd .ci && npm install && DOCKER_BUILDKIT=1 dcl-up services-transactions-server
    - dcl-sync-release
