version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: transactions-server-postgres
    environment:
      POSTGRES_USER: transactions
      POSTGRES_PASSWORD: transactions
      POSTGRES_DB: transactions_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U transactions -d transactions_db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
