name: node

on:
  push:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # @v4.3.0
      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 24
          cache: npm
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: linter
        run: npm run lint
        if: ${{ always() }}
      - name: Test
        run: npm run test
      - name: Report coverage
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # @master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
